CREATE DATABASE POS;
USE POS;

CREATE TABLE MEALS(
    id INT PRIMAY KEY AUTO_INCTEMENT,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    category VARCHAR(150) NOT NULL,
    available  BOOLEAN DEFAULT FALSE,
    img VARCHAR(555) NOT NULL
)

CREATE TABLE ORDERS(
    id INT PRIMAY KEY AUTO_INCTEMENT,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ORDER_ITEMS(
    id INT PRIMAY KEY AUTO_INCTEMENT,
    order_id int NOT NULL,
    meals_id INT NOT NULL,
    quantity INT DEFAULT 1,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id),
    FOREIGN KEY (meals_id) REFERENCES MEALS(id)
);


CREATE TABLE PAYMENT(
    id INT PRIMAY KEY AUTO_INCTEMENT,
    order_id int NOT NULL,
    gross DECIMAL(10,2) NOT NULL,
    tax DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id)
);